### ISSUE TITLE
Visual bug: showing workspace label despite there being no other apps on that workspace

### ISSUE THREAD

**Issue by TuTiuTe** [fthx/task-up#4]
I do not use my other workspaces however task up still indicates the other workspace

the issue is resolved by "refreshing" the extension (toggling on and off some settings, suspending and waking up the computer)

here the issue
![image](https://github.com/user-attachments/assets/7ef1f79b-4563-4926-95a6-bf906471eff2)

after disabling and reenabling "show activities indicator"
![image](https://github.com/user-attachments/assets/dceac155-e064-4557-bf8d-b14d3fe58df7)

**Comment by fthx** [comment]
I'm rewriting the buttons positioning code atm.
There are some other issues. I'm testing the new code and it seems to be ok now.

So stay tuned. But I agree that this taskbar is absolutely not normal, whatever your settings!

**Comment by TuTiuTe** [comment]
Thx for the fast reply! will look forward for the next update :)

**Comment by fthx** [comment]
Are you able to use the new code I've just uploaded?
Just extension.js has been changed.
(Sorry I don't know your GNOME Shell skills!)

**Comment by fthx** [comment]
That's uploaded in GitHub only, not GS website.

**Comment by TuTiuTe** [comment]
I replaced extensions.js in ~/.local/share/gnome-shell/extensions/task-up@fthx with the new one although the bug persists

**Comment by fthx** [comment]
Yep, that's because the taskbar is not correctly destroyed.
I'm on this.
Please check if buttons order is now ok though.

**Comment by TuTiuTe** [comment]
This state is when I turn on my computer
![image](https://github.com/user-attachments/assets/4c7d8a71-dac5-481d-9d0c-b0d85cf10054)
This state is after putting it to sleep and waking it up
![image](https://github.com/user-attachments/assets/9a12d712-a5c7-414d-960f-f8ada1025dcd)

seems to be a little inconsistent when I get this bug, I don't know if this is what you meant by button order or if it's a whole different issue

**Comment by fthx** [comment]
ATM the taskbar is not correctly destroyed (as I wrote).
So when you're sleep/wake up or lock/unlock, extension is disabled then enabled and it's not ok atm.

**Comment by TuTiuTe** [comment]
That also explains why the extension is still active on the log in screen after wake up and why apps stay on the task bar even when disabling the extension

**Comment by fthx** [comment]
Should be solved by:
https://github.com/fthx/task-up/commit/65b3aae1ee8c9ebd1320ee724d71a62238fdcbf8
Could you try this?

I look now at your ghost window bug.

**Comment by TuTiuTe** [comment]
Testing your latest extension.js and it seems like I still have the issue I was first describing
![image](https://github.com/user-attachments/assets/d7acd197-c878-4b4c-9929-2b65f959ebab)
The 2 in the taskbar still remains

**Comment by TuTiuTe** [comment]
I am probably doing something wrong replacing the extension.js, I have no experience with gnome extensions
I'll wait for the next update to see if the problem persists with it properly installed

**Comment by fthx** [comment]
Did you restart your GS session?

**Comment by fthx** [comment]
FYI extension is now online as an update

**Comment by TuTiuTe** [comment]
after updating and even restarting the pc, I still have the issue
I reinstalled Desktop Icons to see if the other issue also persisted and it does too
![Screenshot from 2024-07-31 22-59-50](https://github.com/user-attachments/assets/98993cb8-8f30-42c5-ae93-d30ff566324f)

**Comment by fthx** [comment]
Mmmh I think you installed new metadata.json here with v999 so you did not get the update.

Simple way: uninstall then reinstall TaskUp.

**Comment by TuTiuTe** [comment]
seems to be working? after the reinstall it didn't work right away but after one restart it did, I'll  let you know if it doesn't work
